
import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import SignatureCanvas from "./SignatureCanvas";
import { Idea } from "@/types";

interface AgreementDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  idea: Idea | null;
  onSignAgreement: (signatureData: string) => void;
  isLoading: boolean;
}

const AgreementDialog = ({ 
  open, 
  onOpenChange, 
  idea, 
  onSignAgreement, 
  isLoading 
}: AgreementDialogProps) => {
  const [signatureData, setSignatureData] = useState<string | null>(null);
  
  const handleSignatureChange = (data: string) => {
    setSignatureData(data);
  };
  
  const handleSubmit = () => {
    if (signatureData) {
      onSignAgreement(signatureData);
    }
  };
  
  if (!idea) return null;
  
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle>Investment Agreement for "{idea.title}"</DialogTitle>
          <DialogDescription>
            Please review the terms and sign the agreement below.
          </DialogDescription>
        </DialogHeader>
        
        <div className="my-6 max-h-60 overflow-y-auto border p-4 rounded bg-muted/30 text-sm">
          <h3 className="font-bold text-lg mb-2">Investment Agreement</h3>
          <p className="mb-4">This Agreement (the "Agreement") is made between the investor (hereinafter referred to as "Investor") and the idea owner (hereinafter referred to as "Idea Owner").</p>
          
          <h4 className="font-bold mt-4 mb-2">1. Purpose</h4>
          <p>The purpose of this Agreement is to establish the terms and conditions under which the Investor will provide funding for the development of the idea titled "{idea.title}" (the "Project").</p>
          
          <h4 className="font-bold mt-4 mb-2">2. Investment Amount</h4>
          <p>The Investor agrees to invest the sum of ${idea.estimatedPrice?.toLocaleString()} (the "Investment Amount") in the Project.</p>
          
          <h4 className="font-bold mt-4 mb-2">3. Ownership and Profit Sharing</h4>
          <p>In consideration for the Investment Amount, the Investor shall receive a 30% ownership stake in the Project and shall be entitled to 30% of all profits generated by the Project.</p>
          
          <h4 className="font-bold mt-4 mb-2">4. Governance</h4>
          <p>Major decisions regarding the Project shall require the approval of both the Investor and the Idea Owner.</p>
          
          <h4 className="font-bold mt-4 mb-2">5. Term</h4>
          <p>This Agreement shall remain in effect until terminated by mutual agreement of the parties or as provided herein.</p>
          
          <h4 className="font-bold mt-4 mb-2">6. Confidentiality</h4>
          <p>Both parties agree to maintain the confidentiality of all proprietary information related to the Project.</p>
        </div>
        
        <SignatureCanvas onSave={handleSignatureChange} width={760} height={200} />
        
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button 
            onClick={handleSubmit} 
            disabled={!signatureData || isLoading}
          >
            {isLoading ? "Submitting..." : "Sign Agreement"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default AgreementDialog;
