
import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import SignatureCanvas from "./SignatureCanvas";
import { Idea } from "@/types";
import { Scroll } from "lucide-react";

interface AgreementDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  idea: Idea | null;
  onSignAgreement: (signatureData: string) => void;
  isLoading: boolean;
}

const AgreementDialog = ({ 
  open, 
  onOpenChange, 
  idea, 
  onSignAgreement, 
  isLoading 
}: AgreementDialogProps) => {
  const [signatureData, setSignatureData] = useState<string | null>(null);
  
  const handleSignatureChange = (data: string) => {
    setSignatureData(data);
  };
  
  const handleSubmit = () => {
    if (signatureData) {
      onSignAgreement(signatureData);
    }
  };
  
  if (!idea) return null;
  
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader className="pb-2 border-b">
          <DialogTitle className="flex items-center gap-2 text-xl">
            <Scroll className="h-5 w-5 text-primary" />
            Investment Agreement for "{idea.title}"
          </DialogTitle>
          <DialogDescription className="text-muted-foreground">
            Please review the terms and sign the agreement below.
          </DialogDescription>
        </DialogHeader>
        
        <div className="my-4 overflow-y-auto border rounded-md bg-muted/20 text-sm flex-1">
          <div className="p-6">
            <h3 className="font-bold text-xl mb-4 text-primary">Investment Agreement</h3>
            <p className="mb-4 leading-relaxed">This Agreement (the "Agreement") is made between the investor (hereinafter referred to as "Investor") and the idea owner (hereinafter referred to as "Idea Owner").</p>
            
            <h4 className="font-bold mt-6 mb-2 text-lg">1. Purpose</h4>
            <p className="leading-relaxed">The purpose of this Agreement is to establish the terms and conditions under which the Investor will provide funding for the development of the idea titled "{idea.title}" (the "Project").</p>
            
            <h4 className="font-bold mt-6 mb-2 text-lg">2. Investment Amount</h4>
            <p className="leading-relaxed">The Investor agrees to invest the sum of ${idea.estimatedPrice?.toLocaleString()} (the "Investment Amount") in the Project.</p>
            
            <h4 className="font-bold mt-6 mb-2 text-lg">3. Ownership and Profit Sharing</h4>
            <p className="leading-relaxed">In consideration for the Investment Amount, the Investor shall receive a 30% ownership stake in the Project and shall be entitled to 30% of all profits generated by the Project.</p>
            
            <h4 className="font-bold mt-6 mb-2 text-lg">4. Governance</h4>
            <p className="leading-relaxed">Major decisions regarding the Project shall require the approval of both the Investor and the Idea Owner.</p>
            
            <h4 className="font-bold mt-6 mb-2 text-lg">5. Term</h4>
            <p className="leading-relaxed">This Agreement shall remain in effect until terminated by mutual agreement of the parties or as provided herein.</p>
            
            <h4 className="font-bold mt-6 mb-2 text-lg">6. Confidentiality</h4>
            <p className="leading-relaxed">Both parties agree to maintain the confidentiality of all proprietary information related to the Project.</p>
            
            <h4 className="font-bold mt-6 mb-2 text-lg">7. Signatures</h4>
            <p className="leading-relaxed">By signing below, both parties acknowledge that they have read, understood, and agree to be bound by the terms and conditions set forth in this Agreement.</p>
          </div>
        </div>
        
        <div className="border-t pt-4">
          <h4 className="font-medium mb-2 text-muted-foreground">Your Signature</h4>
          <SignatureCanvas onSave={handleSignatureChange} width={760} height={200} />
        </div>
        
        <DialogFooter className="pt-2 border-t mt-4">
          <Button 
            variant="outline" 
            onClick={() => onOpenChange(false)}
            className="border-gray-300 hover:bg-gray-100"
          >
            Cancel
          </Button>
          <Button 
            onClick={handleSubmit} 
            disabled={!signatureData || isLoading}
            className="bg-primary hover:bg-primary/90"
          >
            {isLoading ? "Processing..." : "Sign Agreement"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default AgreementDialog;
