
import { Idea, Agreement } from "@/types";
import { renderAgreementContent } from "@/components/AgreementDialog";

/**
 * Opens a new window with the agreement as a PDF
 */
export const openAgreementPdf = (agreement: Agreement) => {
  if (!agreement.idea) {
    console.error("Cannot generate PDF: Agreement has no associated idea");
    return;
  }

  // Create a URL for the PDF viewing page
  const pdfUrl = `/pdf-viewer?agreementId=${agreement.id}`;
  
  // Open the PDF in a new tab
  window.open(pdfUrl, "_blank");
};

/**
 * Generate HTML content for an agreement PDF
 */
export const generateAgreementHtml = (
  agreement: Agreement, 
  signatureData?: string
): string => {
  if (!agreement.idea) {
    return "<p>Error: Agreement has no associated idea</p>";
  }

  const idea = agreement.idea;
  const signedDate = agreement.signedAt 
    ? new Date(agreement.signedAt).toLocaleDateString() 
    : "Pending";

  return `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <h1 style="text-align: center; color: #1a56db;">Investment Agreement</h1>
      <h2 style="text-align: center; margin-bottom: 30px;">${idea.title}</h2>
      
      <div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 30px;">
        <h3 style="font-size: 18px; margin-bottom: 15px; color: #1a56db;">Investment Agreement</h3>
        <p style="line-height: 1.6;">This Agreement (the "Agreement") is made between the investor (hereinafter referred to as "Investor") and the idea owner (hereinafter referred to as "Idea Owner").</p>
        
        <h4 style="font-size: 16px; margin-top: 25px; margin-bottom: 10px;">1. Purpose</h4>
        <p style="line-height: 1.6;">The purpose of this Agreement is to establish the terms and conditions under which the Investor will provide funding for the development of the idea titled "${idea.title}" (the "Project").</p>
        
        <h4 style="font-size: 16px; margin-top: 25px; margin-bottom: 10px;">2. Investment Amount</h4>
        <p style="line-height: 1.6;">The Investor agrees to invest the sum of $${idea.estimatedPrice?.toLocaleString()} (the "Investment Amount") in the Project.</p>
        
        <h4 style="font-size: 16px; margin-top: 25px; margin-bottom: 10px;">3. Ownership and Profit Sharing</h4>
        <p style="line-height: 1.6;">In consideration for the Investment Amount, the Investor shall receive a 30% ownership stake in the Project and shall be entitled to 30% of all profits generated by the Project.</p>
        
        <h4 style="font-size: 16px; margin-top: 25px; margin-bottom: 10px;">4. Governance</h4>
        <p style="line-height: 1.6;">Major decisions regarding the Project shall require the approval of both the Investor and the Idea Owner.</p>
        
        <h4 style="font-size: 16px; margin-top: 25px; margin-bottom: 10px;">5. Term</h4>
        <p style="line-height: 1.6;">This Agreement shall remain in effect until terminated by mutual agreement of the parties or as provided herein.</p>
        
        <h4 style="font-size: 16px; margin-top: 25px; margin-bottom: 10px;">6. Confidentiality</h4>
        <p style="line-height: 1.6;">Both parties agree to maintain the confidentiality of all proprietary information related to the Project.</p>
      </div>
      
      <div style="margin-top: 30px;">
        <h4 style="font-size: 16px; margin-bottom: 10px;">Signatures</h4>
        <p style="line-height: 1.6;">Date signed: ${signedDate}</p>
        
        ${signatureData ? `
          <div style="margin-top: 20px;">
            <p style="margin-bottom: 10px;">Investor Signature:</p>
            <img src="${signatureData}" alt="Investor Signature" style="max-width: 300px; border-bottom: 1px solid #000;" />
          </div>
        ` : ''}
        
        <div style="margin-top: 20px;">
          <p style="margin-bottom: 10px;">Idea Owner Signature:</p>
          <div style="height: 60px; border-bottom: 1px solid #000; width: 300px;"></div>
        </div>
      </div>
    </div>
  `;
};
