
import { Agreement } from "@/types";

/**
 * Opens a new window with the agreement as a PDF
 */
export const openAgreementPdf = (agreement: Agreement) => {
  if (!agreement.idea) {
    console.error("Cannot generate PDF: Agreement has no associated idea");
    return;
  }

  // Create a URL for the PDF viewing page
  const pdfUrl = `/pdf-viewer?agreementId=${agreement.id}`;
  
  // Open the PDF in a new tab
  window.open(pdfUrl, "_blank");
};

/**
 * Generate HTML content for an agreement PDF
 */
export const generateAgreementHtml = (
  agreement: Agreement, 
  signatureData?: string
): string => {
  if (!agreement.idea) {
    return "<p>Error: Agreement has no associated idea</p>";
  }

  const idea = agreement.idea;
  const signedDate = agreement.signedAt 
    ? new Date(agreement.signedAt).toLocaleDateString() 
    : "Pending";

  // Create a unique document ID
  const documentId = `INV-${Math.floor(Math.random() * 1000000).toString().padStart(6, '0')}`;

  return `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <div style="display: flex; align-items: center; margin-bottom: 30px;">
        <div style="background-color: rgba(26, 86, 219, 0.1); padding: 10px; border-radius: 50%; margin-right: 15px;">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#1a56db" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
            <path d="M14 2v6h6"></path>
            <path d="M16 13H8"></path>
            <path d="M16 17H8"></path>
            <path d="M10 9H8"></path>
          </svg>
        </div>
        <div>
          <h1 style="margin: 0; color: #1a56db; font-size: 24px;">Investment Agreement</h1>
          <p style="margin: 5px 0 0; color: #6b7280; font-size: 14px;">Document ID: ${documentId}</p>
        </div>
      </div>
      
      <div style="background: linear-gradient(to bottom, rgba(26, 86, 219, 0.05), transparent); padding: 25px; border-radius: 8px; margin-bottom: 30px;">
        <p style="line-height: 1.6; margin-bottom: 20px;">This Agreement (the "Agreement") is made between the investor (hereinafter referred to as "Investor") and the idea owner (hereinafter referred to as "Idea Owner").</p>
        
        <div style="margin-bottom: 25px;">
          <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <div style="display: flex; align-items: center; justify-content: center; width: 24px; height: 24px; background-color: rgba(26, 86, 219, 0.1); border-radius: 50%; margin-right: 10px;">
              <span style="font-size: 12px; color: #1a56db;">1</span>
            </div>
            <h3 style="margin: 0; font-size: 18px; color: #111827;">Purpose</h3>
          </div>
          <p style="line-height: 1.6; margin-left: 34px;">The purpose of this Agreement is to establish the terms and conditions under which the Investor will provide funding for the development of the idea titled "${idea.title || 'Untitled'}" (the "Project").</p>
        </div>
        
        <div style="margin-bottom: 25px;">
          <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <div style="display: flex; align-items: center; justify-content: center; width: 24px; height: 24px; background-color: rgba(26, 86, 219, 0.1); border-radius: 50%; margin-right: 10px;">
              <span style="font-size: 12px; color: #1a56db;">2</span>
            </div>
            <h3 style="margin: 0; font-size: 18px; color: #111827;">Investment Amount</h3>
          </div>
          <p style="line-height: 1.6; margin-left: 34px;">The Investor agrees to invest the sum of $${(idea.estimatedPrice || 0).toLocaleString()} (the "Investment Amount") in the Project.</p>
        </div>
        
        <div style="margin-bottom: 25px;">
          <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <div style="display: flex; align-items: center; justify-content: center; width: 24px; height: 24px; background-color: rgba(26, 86, 219, 0.1); border-radius: 50%; margin-right: 10px;">
              <span style="font-size: 12px; color: #1a56db;">3</span>
            </div>
            <h3 style="margin: 0; font-size: 18px; color: #111827;">Ownership and Profit Sharing</h3>
          </div>
          <p style="line-height: 1.6; margin-left: 34px;">In consideration for the Investment Amount, the Investor shall receive a 30% ownership stake in the Project and shall be entitled to 30% of all profits generated by the Project.</p>
        </div>
        
        <div style="margin-bottom: 25px;">
          <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <div style="display: flex; align-items: center; justify-content: center; width: 24px; height: 24px; background-color: rgba(26, 86, 219, 0.1); border-radius: 50%; margin-right: 10px;">
              <span style="font-size: 12px; color: #1a56db;">4</span>
            </div>
            <h3 style="margin: 0; font-size: 18px; color: #111827;">Governance</h3>
          </div>
          <p style="line-height: 1.6; margin-left: 34px;">Major decisions regarding the Project shall require the approval of both the Investor and the Idea Owner.</p>
        </div>
        
        <div style="margin-bottom: 25px;">
          <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <div style="display: flex; align-items: center; justify-content: center; width: 24px; height: 24px; background-color: rgba(26, 86, 219, 0.1); border-radius: 50%; margin-right: 10px;">
              <span style="font-size: 12px; color: #1a56db;">5</span>
            </div>
            <h3 style="margin: 0; font-size: 18px; color: #111827;">Term</h3>
          </div>
          <p style="line-height: 1.6; margin-left: 34px;">This Agreement shall remain in effect until terminated by mutual agreement of the parties or as provided herein.</p>
        </div>
        
        <div style="margin-bottom: 25px;">
          <div style="display: flex; align-items: center; margin-bottom: 10px;">
            <div style="display: flex; align-items: center; justify-content: center; width: 24px; height: 24px; background-color: rgba(26, 86, 219, 0.1); border-radius: 50%; margin-right: 10px;">
              <span style="font-size: 12px; color: #1a56db;">6</span>
            </div>
            <h3 style="margin: 0; font-size: 18px; color: #111827;">Confidentiality</h3>
          </div>
          <p style="line-height: 1.6; margin-left: 34px;">Both parties agree to maintain the confidentiality of all proprietary information related to the Project.</p>
        </div>
        
        <div style="display: flex; align-items: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#10b981" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
            <polyline points="22 4 12 14.01 9 11.01"></polyline>
          </svg>
          <span style="font-size: 14px; color: #6b7280; margin-left: 8px;">This agreement is legally binding once signed by both parties</span>
        </div>
      </div>
      
      <div style="margin-top: 30px;">
        <h4 style="font-size: 18px; margin-bottom: 15px; color: #111827;">Signatures</h4>
        <p style="line-height: 1.6; margin-bottom: 20px;">Date signed: ${signedDate}</p>
        
        ${signatureData ? `
          <div style="margin-top: 20px;">
            <p style="margin-bottom: 10px; font-weight: 500;">Investor Signature:</p>
            <img src="${signatureData}" alt="Investor Signature" style="max-width: 300px; max-height: 80px; border-bottom: 1px solid #e5e7eb; padding-bottom: 10px;" />
            <p style="margin-top: 5px; font-size: 14px; color: #6b7280;">Electronically signed</p>
          </div>
        ` : ''}
        
        <div style="margin-top: 30px;">
          <p style="margin-bottom: 10px; font-weight: 500;">Idea Owner Signature:</p>
          <div style="height: 60px; border-bottom: 1px solid #e5e7eb; width: 300px;"></div>
          <p style="margin-top: 5px; font-size: 14px; color: #6b7280;">Pending</p>
        </div>
      </div>
      
      <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center;">
        <p style="font-size: 14px; color: #6b7280;">This document was generated on ${new Date().toLocaleDateString()} and is stored securely.</p>
      </div>
    </div>
  `;
};
