// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zezvzfandofxbtxtblnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplenZ6ZmFuZG9meGJ0eHRibG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDY4MzksImV4cCI6MjA1NzY4MjgzOX0.UagcblpKbPY-05sYNG4Kc9SOwPUDmC4b2XDt0AY3y-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);